parameters:
#    urbanet_media.example.class: Urbanet\MediaBundle\Example

services:
#    urbanet_media.example:
#        class: %urbanet_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
