parameters:
#    urbanet_event.example.class: Urbanet\EventBundle\Example

services:
#    urbanet_event.example:
#        class: %urbanet_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
