parameters:
#    urbanet_annonce.example.class: Urbanet\AnnonceBundle\Example

services:
#    urbanet_annonce.example:
#        class: %urbanet_annonce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
